IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'AppTesteDB')
BEGIN
    CREATE DATABASE AppTesteDB;
    ALTER DATABASE AppTesteDB SET READ_COMMITTED_SNAPSHOT ON;
END
GO

USE AppTesteDB;
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_CLIENTE')
BEGIN
    CREATE TABLE TB_CLIENTE (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        NOME VARCHAR(150),
        RG VARCHAR(20),
        CPF VARCHAR(20),
        DATA_NASCIMENTO DATE,
        TELEFONE VARCHAR(20),
        EMAIL VARCHAR(150),
        COD_EMPRESA INT
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_CIDADE')
BEGIN
    CREATE TABLE TB_CIDADE (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        NOME VARCHAR(100),
        ESTADO CHAR(2)
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_ENDERECO')
BEGIN
    CREATE TABLE TB_ENDERECO (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        RUA VARCHAR(255),
        BAIRRO VARCHAR(50),
        NUMERO VARCHAR(50),
        COMPLEMENTO VARCHAR(100),
        CEP VARCHAR(10),
        TIPO_ENDERECO INT,
        TB_CIDADE_ID INT
    );

    ALTER TABLE TB_ENDERECO
        ADD CONSTRAINT FK_TB_ENDERECO_TB_CIDADE2
        FOREIGN KEY (TB_CIDADE_ID) REFERENCES TB_CIDADE(ID)
END
GO

IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'TB_CLIENTE_ENDERECO')
BEGIN
    CREATE TABLE TB_CLIENTE_ENDERECO (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        TB_CLIENTE_ID INT,
        TB_ENDERECO_ID INT
    );
    ALTER TABLE TB_CLIENTE_ENDERECO
        ADD CONSTRAINT FK_TB_CLIENTE_ENDERECO_TB_CLIENTE2
        FOREIGN KEY (TB_CLIENTE_ID) REFERENCES TB_CLIENTE(ID);

    ALTER TABLE TB_CLIENTE_ENDERECO
        ADD CONSTRAINT FK_TB_CLIENTE_ENDERECO_TB_ENDERECO2
        FOREIGN KEY (TB_ENDERECO_ID) REFERENCES TB_ENDERECO(ID);
END
GO